#!/usr/bin/env bash
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Manhattan" "New York" "USA" 50;
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Los Angeles" "California" "USA" 50;
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Chicago" "Illinois" "USA" 50;
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Houston" "Texas" "USA" 50;
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Philadelphia" "Pennsylvania" "USA" 50;
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Phoenix" "Arizona" "USA" 50;
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "San Diego" "California" "USA" 50;
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Dallas" "Texas" "USA" 50;
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "San Diego" "Texas" "USA" 50;
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Detroit" "Michigan" "USA" 50;
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "San Jose" "California" "USA" 50;
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Indianapolis" "Indiana" "USA" 50;
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "San Francisco" "California" "USA" 50;
#java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Jacksonville" "Florida" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Columbus" "Ohio" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Austin" "Texas" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Memphis" "Tennessee" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Baltimore" "Maryland" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Milwaukee" "Wisconsin" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Boston" "Massachusetts" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Charlotte" "North Carolina" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "El Paso" "Texas" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Washington" "District of Columbia" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Nashville-Davidson" "Tennessee" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Seattle" "Washington" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Fort Worth" "Texas" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Denver" "Colorado" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Portland" "Oregon" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Oklahoma" "Oklahoma" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Las Vegas" "Nevada" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Tucson" "Arizona" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "New Orleans" "Louisiana" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Long Beach" "California" "USA" 50;
java -jar /Users/joshuaking/IdeaProjects/RestaurantContactInfoScraper/target/RestaurantContactInfoScraper.jar /Users/joshuaking/FactualData "Cleveland" "Ohio" "USA" 50;